/* Vocabulario Shorashim — extraído del PDF del usuario (181 términos)
   en: inglés · es: español · fr: francés */
export const WORDS = [
{ he: 'פָּנִים', en: 'faces, inside', es: 'caras, interior', fr: 'visages, intérieur' },
{ he: 'בֵּין', en: 'between', es: 'entre', fr: 'entre' },
{ he: 'קָרָא', en: 'call, read', es: 'llamar, leer', fr: 'appeler, lire' },
{ he: 'יוֹם', en: 'day', es: 'día', fr: 'jour' },
{ he: 'לַיְלָה', en: 'night', es: 'noche', fr: 'nuit' },
{ he: 'עֶרֶב', en: 'evening', es: 'tarde, atardecer', fr: 'soir' },
{ he: 'בֹּקֶר', en: 'morning', es: 'mañana', fr: 'matin' },
{ he: 'אֶחָד', en: 'one', es: 'uno', fr: 'un' },
{ he: 'רָקִיעַ', en: 'sky', es: 'cielo, firmamento', fr: 'ciel, firmament' },
{ he: 'תּוֹךְ', en: 'middle, midst', es: 'medio, en medio de', fr: 'milieu, au milieu de' },
{ he: 'עָשָׂה', en: 'made, do', es: 'hizo, hacer', fr: 'fit, faire' },
{ he: 'אֲשֶׁר', en: 'that, which', es: 'que, el cual', fr: 'que, lequel' },
{ he: 'תַּחַת', en: 'under', es: 'debajo de', fr: 'sous' },
{ he: 'כֵּן', en: 'so', es: 'así', fr: 'ainsi' },
{ he: 'שֵׁנִי', en: 'second', es: 'segundo', fr: 'deuxième' },
{ he: 'מִקְוֶה', en: 'collection of water', es: 'acumulación de agua', fr: "amas d'eau" },
{ he: 'מָקוֹם', en: 'place', es: 'lugar', fr: 'lieu' },
{ he: 'יַבָּשָׁה', en: 'dry land', es: 'tierra seca', fr: 'terre sèche' },
{ he: 'יָם', en: 'sea, ocean', es: 'mar, océano', fr: 'mer, océan' },
{ he: 'עֵשֶׂב', en: 'grass', es: 'hierba', fr: 'herbe' },
{ he: 'זֶרַע', en: 'seed', es: 'semilla', fr: 'semence' },
{ he: 'עֵץ', en: 'tree', es: 'árbol', fr: 'arbre' },
{ he: 'פְּרִי', en: 'fruit', es: 'fruto', fr: 'fruit' },
{ he: 'מִין', en: 'type, kind', es: 'tipo, especie', fr: 'type, espèce' },
{ he: 'יָצָא', en: 'go out', es: 'salir', fr: 'sortir' },
{ he: 'שְׁלִישִׁי', en: 'third', es: 'tercero', fr: 'troisième' },
{ he: 'אוֹת', en: 'sign, letter', es: 'señal, letra', fr: 'signe, lettre' },
{ he: 'מוֹעֲדִים', en: 'seasons', es: 'estaciones, festividades', fr: 'saisons, fêtes' },
{ he: 'שָׁנָה', en: 'year', es: 'año', fr: 'année' },
{ he: 'גָּדוֹל', en: 'big, great, independent, adult', es: 'grande, independiente, adulto', fr: 'grand, indépendant, adulte' },
{ he: 'קָטָן', en: 'small, child', es: 'pequeño, niño', fr: 'petit, enfant' },
{ he: 'כּוֹכָב', en: 'star', es: 'estrella', fr: 'étoile' },
{ he: 'נָתַן', en: 'give', es: 'dar', fr: 'donner' },
{ he: 'רְבִיעִי', en: 'fourth', es: 'cuarto', fr: 'quatrième' },
{ he: 'שֶׁרֶץ', en: 'crawler', es: 'reptil, bicho que repta', fr: 'bestiole rampante' },
{ he: 'נֶפֶשׁ', en: 'soul', es: 'alma', fr: 'âme' },
{ he: 'חַי', en: 'life', es: 'vida', fr: 'vie' },
{ he: 'עוֹף', en: 'bird', es: 'ave', fr: 'oiseau' },
{ he: 'תַּנִּינִם', en: 'giant fish', es: 'peces gigantes', fr: 'poissons géants' },
{ he: 'כֹּל', en: 'all, every', es: 'todo, cada', fr: 'tout, chaque' },
{ he: 'רָמַשׂ', en: 'creep', es: 'reptar', fr: 'ramper' },
{ he: 'כָּנָף', en: 'wing, corner', es: 'ala, esquina', fr: 'aile, coin' },
{ he: 'בֵּרֵךְ', en: 'bless', es: 'bendecir', fr: 'bénir' },
{ he: 'רַב', en: 'many, multiple, increase', es: 'muchos, multiplicar, aumentar', fr: 'nombreux, multiplier, augmenter' },
{ he: 'מָלֵא', en: 'full', es: 'lleno', fr: 'plein' },
{ he: 'חֲמִישִׁי', en: 'fifth', es: 'quinto', fr: 'cinquième' },
{ he: 'בְּהֵמָה', en: 'domestic animal', es: 'animal doméstico', fr: 'animal domestique' },
{ he: 'חַיָּה', en: 'wild animal', es: 'animal salvaje', fr: 'animal sauvage' },
{ he: 'אָדָם', en: 'man', es: 'hombre', fr: 'homme' },
{ he: 'צֶלֶם', en: 'reflection', es: 'reflejo, imagen', fr: 'reflet, image' },
{ he: 'יָרַד', en: 'go down, descend', es: 'bajar, descender', fr: 'descendre' },
{ he: 'דָּג', en: 'fish', es: 'pez', fr: 'poisson' },
{ he: 'זָכָר', en: 'male', es: 'macho, varón', fr: 'mâle' },
{ he: 'נְקֵבָה', en: 'female', es: 'hembra', fr: 'femelle' },
{ he: 'הִנֵּה', en: 'behold, pay attention', es: 'he aquí, presta atención', fr: 'voici, fais attention' },
{ he: 'אוֹכֶל', en: 'eat', es: 'comer', fr: 'manger' },
{ he: 'יֶרֶק', en: 'vegetable', es: 'verdura', fr: 'légume' },
{ he: 'מְאֹד', en: 'very', es: 'muy', fr: 'très' },
{ he: 'שִׁשִּׁי', en: 'sixth', es: 'sexto', fr: 'sixième' },
{ he: 'צָבָא', en: 'army, stars', es: 'ejército, astros', fr: 'armée, astres' },
{ he: 'שְׁבִיעִי', en: 'seventh', es: 'séptimo', fr: 'septième' },
{ he: 'מְלָאכָה', en: 'work', es: 'trabajo, labor', fr: 'travail' },
{ he: 'שַׁבָּת', en: 'Shabbat, rest', es: 'Shabat, descanso', fr: 'Chabbat, repos' },
{ he: 'קֹדֶשׁ', en: 'special, unique, holy', es: 'especial, único, santo', fr: 'spécial, unique, saint' },
{ he: 'תּוֹלְדָה', en: 'generations, events', es: 'generaciones, sucesos', fr: 'générations, événements' },
{ he: 'יְיָ', en: 'Hashem, the eternal one', es: 'Hashem, el Eterno', fr: "Hachem, l'Éternel" },
{ he: 'שִׂיחַ', en: 'growth', es: 'vegetación, arbusto', fr: 'végétation, arbuste' },
{ he: 'שָׂדֶה', en: 'field', es: 'campo', fr: 'champ' },
{ he: 'טֶרֶם', en: 'not yet', es: 'todavía no', fr: 'pas encore' },
{ he: 'צֶמַח', en: 'sprout', es: 'brote', fr: 'pousse' },
{ he: 'לֹא', en: 'no', es: 'no', fr: 'non' },
{ he: 'מָטָר', en: 'rain', es: 'lluvia', fr: 'pluie' },
{ he: 'אַיִן', en: 'not', es: 'no hay', fr: "il n'y a pas" },
{ he: 'עָבַד', en: 'serve, work', es: 'servir, trabajar', fr: 'servir, travailler' },
{ he: 'אֲדָמָה', en: 'earth', es: 'tierra, suelo', fr: 'terre, sol' },
{ he: 'אֵד', en: 'mist', es: 'neblina, vapor', fr: 'brume, vapeur' },
{ he: 'מִן', en: 'from', es: 'de, desde', fr: 'de, depuis' },
{ he: 'מַשְׁקֶה', en: 'watered, drink', es: 'regado, bebida', fr: 'arrosé, boisson' },
{ he: 'יָצַר', en: 'designed', es: 'formó, diseñó', fr: 'forma, façonna' },
{ he: 'אֵלֶּה', en: 'these', es: 'estos', fr: 'ceux-ci' },
{ he: 'רֹאשׁ', en: 'head', es: 'cabeza', fr: 'tête' },
{ he: 'בָּרָא', en: 'create', es: 'crear', fr: 'créer' },
{ he: 'אלקים', en: 'Hashem / power of all powers', es: 'Hashem / poder de todos los poderes', fr: 'Hachem / puissance de toutes les puissances' },
{ he: 'שָׁמַיִם', en: 'heavens', es: 'cielos', fr: 'cieux' },
{ he: 'אֶרֶץ', en: 'land, earth', es: 'tierra, país', fr: 'terre, pays' },
{ he: 'הָיָה', en: 'was, exist', es: 'fue, existir', fr: 'fut, exister' },
{ he: 'חֹשֶׁךְ', en: 'darkness', es: 'oscuridad', fr: 'obscurité' },
{ he: 'עַל', en: 'on', es: 'sobre', fr: 'sur' },
{ he: 'רוּחַ', en: 'wind, spirit', es: 'viento, espíritu', fr: 'vent, esprit' },
{ he: 'אָמַר', en: 'said', es: 'dijo', fr: 'dit' },
{ he: 'מַיִם', en: 'water', es: 'agua', fr: 'eau' },
{ he: 'אוֹר', en: 'light', es: 'luz', fr: 'lumière' },
{ he: 'רָאָה', en: 'see', es: 'ver', fr: 'voir' },
{ he: 'כִּי', en: 'that, because, when', es: 'que, porque, cuando', fr: 'que, parce que, quand' },
{ he: 'טוֹב', en: 'good', es: 'bueno', fr: 'bon' },
{ he: 'הִבְדִּיל', en: 'divide, separate', es: 'dividir, separar', fr: 'diviser, séparer' },
{ he: 'עָפָר', en: 'dust', es: 'polvo', fr: 'poussière' },
{ he: 'נָפַח', en: 'blew', es: 'sopló', fr: 'souffla' },
{ he: 'אַף', en: 'nose, anger', es: 'nariz, enojo', fr: 'nez, colère' },
{ he: 'נְשָׁמָה', en: 'soul', es: 'alma', fr: 'âme' },
{ he: 'נָטַע', en: 'plant', es: 'plantar', fr: 'planter' },
{ he: 'גַּן', en: 'garden', es: 'jardín, huerto', fr: 'jardin' },
{ he: 'קֶדֶם', en: 'east', es: 'este, oriente', fr: 'est, orient' },
{ he: 'שִׂים', en: 'place, put down', es: 'poner, colocar', fr: 'placer, poser' },
{ he: 'שָׁם', en: 'there', es: 'allí', fr: 'là-bas' },
{ he: 'מַרְאֶה', en: 'appearance', es: 'apariencia', fr: 'apparence' },
{ he: 'יָדַע', en: 'know', es: 'saber, conocer', fr: 'savoir, connaître' },
{ he: 'רַע', en: 'bad, evil', es: 'malo, mal', fr: 'mauvais, mal' },
{ he: 'נָהָר', en: 'river', es: 'río', fr: 'fleuve, rivière' },
{ he: 'אַרְבָּעָה', en: 'four', es: 'cuatro', fr: 'quatre' },
{ he: 'פֵּרֵד', en: 'divide', es: 'dividir', fr: 'diviser' },
{ he: 'שֵׁם', en: 'name', es: 'nombre', fr: 'nom' },
{ he: 'הוּא', en: 'he, it is', es: 'él, eso es', fr: "il, c'est" },
{ he: 'סוֹבֵב', en: 'surround', es: 'rodear', fr: 'entourer' },
{ he: 'זָהָב', en: 'gold', es: 'oro', fr: 'or' },
{ he: 'אֶבֶן', en: 'stone', es: 'piedra', fr: 'pierre' },
{ he: 'לָקַח', en: 'take', es: 'tomar', fr: 'prendre' },
{ he: 'שָׁמַר', en: 'guard', es: 'guardar, cuidar', fr: 'garder' },
{ he: 'צִוָּה', en: 'command', es: 'ordenar, mandar', fr: 'ordonner' },
{ he: 'מוֹת', en: 'death', es: 'muerte', fr: 'mort' },
{ he: 'לְבַד', en: 'alone', es: 'solo', fr: 'seul' },
{ he: 'נֶגֶד', en: 'against', es: 'contra, frente a', fr: 'contre, face à' },
{ he: 'בָּא', en: 'come', es: 'venir', fr: 'venir' },
{ he: 'מָה', en: 'what', es: 'qué', fr: 'quoi' },
{ he: 'מָצָא', en: 'find', es: 'encontrar', fr: 'trouver' },
{ he: 'נָפַל', en: 'fall', es: 'caer', fr: 'tomber' },
{ he: 'צֶלַע', en: 'rib', es: 'costilla', fr: 'côte' },
{ he: 'סָגַר', en: 'close', es: 'cerrar', fr: 'fermer' },
{ he: 'בָּשָׂר', en: 'meat, flesh', es: 'carne', fr: 'viande, chair' },
{ he: 'בָּנָה', en: 'build', es: 'construir', fr: 'construire' },
{ he: 'אִשָּׁה', en: 'woman', es: 'mujer', fr: 'femme' },
{ he: 'אֶל', en: 'to', es: 'a, hacia', fr: 'à, vers' },
{ he: 'זֶה, זֹאת', en: 'this', es: 'este, esta', fr: 'ceci' },
{ he: 'פַּעַם', en: 'time', es: 'vez', fr: 'fois' },
{ he: 'עֶצֶם', en: 'bone', es: 'hueso', fr: 'os' },
{ he: 'אִישׁ', en: 'man', es: 'hombre', fr: 'homme' },
{ he: 'עָזַב', en: 'leave', es: 'dejar, abandonar', fr: 'quitter, abandonner' },
{ he: 'אָב', en: 'father', es: 'padre', fr: 'père' },
{ he: 'אֵם', en: 'mother', es: 'madre', fr: 'mère' },
{ he: 'דָּבַק', en: 'glue, cleave', es: 'pegar, adherirse', fr: "coller, s'attacher" },
{ he: 'נָחָשׁ', en: 'snake', es: 'serpiente', fr: 'serpent' },
{ he: 'פָּקַח', en: 'open', es: 'abrir', fr: 'ouvrir' },
{ he: 'עַיִן', en: 'eye', es: 'ojo', fr: 'œil' },
{ he: 'גַּם', en: 'also', es: 'también', fr: 'aussi' },
{ he: 'עָלֶה', en: 'leaf', es: 'hoja', fr: 'feuille' },
{ he: 'תְּאֵנָה', en: 'fig', es: 'higo', fr: 'figue' },
{ he: 'הֵם', en: 'them', es: 'ellos', fr: 'eux' },
{ he: 'שָׁמַע', en: 'listen, hear', es: 'escuchar, oír', fr: 'écouter, entendre' },
{ he: 'קוֹל', en: 'voice', es: 'voz', fr: 'voix' },
{ he: 'הָלַךְ', en: 'go', es: 'ir', fr: 'aller' },
{ he: 'מִפְּנֵי', en: 'because of', es: 'por causa de', fr: 'à cause de' },
{ he: 'יָרֵא', en: 'fear', es: 'temer', fr: 'craindre' },
{ he: 'אָנֹכִי', en: 'I', es: 'yo', fr: 'je, moi' },
{ he: 'אַתָּה', en: 'you', es: 'tú', fr: 'tu, toi' },
{ he: 'עָקֵב', en: 'heel, hold back', es: 'talón, retener', fr: 'talon, retenir' },
{ he: 'הוֹלִיד', en: 'give birth', es: 'engendrar, dar a luz', fr: 'engendrer' },
{ he: 'בֵּן', en: 'son', es: 'hijo', fr: 'fils' },
{ he: 'בַּעֲבוּר', en: 'so that, for the sake of', es: 'para que, por el bien de', fr: 'pour que, en faveur de' },
{ he: 'קוֹץ', en: 'thorn', es: 'espina', fr: 'épine' },
{ he: 'זֵעָה', en: 'sweat', es: 'sudor', fr: 'sueur' },
{ he: 'לֶחֶם', en: 'bread', es: 'pan', fr: 'pain' },
{ he: 'עַד', en: 'until', es: 'hasta', fr: "jusqu'à" },
{ he: 'שׁוּב', en: 'return', es: 'volver, regresar', fr: 'revenir, retourner' },
{ he: 'עוֹר', en: 'skin', es: 'piel', fr: 'peau' },
{ he: 'הֵן', en: 'them', es: 'ellas', fr: 'elles' },
{ he: 'עַתָּה', en: 'now', es: 'ahora', fr: 'maintenant' },
{ he: 'פֶּן', en: 'perhaps, maybe', es: 'quizás, no sea que', fr: 'peut-être, de peur que' },
{ he: 'שָׁלַח', en: 'send', es: 'enviar', fr: 'envoyer' },
{ he: 'יָד', en: 'hand', es: 'mano', fr: 'main' },
{ he: 'לְעוֹלָם', en: 'forever', es: 'para siempre', fr: 'pour toujours' },
{ he: 'חֶרֶב', en: 'sword', es: 'espada', fr: 'épée' },
{ he: 'דֶּרֶךְ', en: 'journey, way, path', es: 'camino, senda', fr: 'chemin, voie' },
{ he: 'הָרָה', en: 'pregnant', es: 'embarazada', fr: 'enceinte' },
{ he: 'קָנָה', en: 'buy, acquire, own', es: 'comprar, adquirir, poseer', fr: 'acheter, acquérir, posséder' },
{ he: 'יָסַף', en: 'add', es: 'añadir', fr: 'ajouter' },
{ he: 'אָח', en: 'brother', es: 'hermano', fr: 'frère' },
{ he: 'רוֹעֶה', en: 'shepherd', es: 'pastor', fr: 'berger' },
{ he: 'צֹאן', en: 'flock', es: 'rebaño', fr: 'troupeau' },
{ he: 'מִנְחָה', en: 'offering', es: 'ofrenda', fr: 'offrande' },
{ he: 'חָרָה', en: 'anger', es: 'enojo, ira', fr: 'colère, courroux' },
{ he: 'לָמָּה', en: 'why, to what, for what purpose', es: 'por qué, para qué', fr: 'pourquoi, dans quel but' },
];

export const N = WORDS.length;

/* dos palabras "chocan" si comparten significado en cualquiera de los idiomas
   (p. ej. אָדָם y אִישׁ = "man"/"hombre"/"homme") — se usa para filtrar distractores */
export function sameMeaning(a, b) {
  return WORDS[a].en === WORDS[b].en
    || WORDS[a].es === WORDS[b].es
    || WORDS[a].fr === WORDS[b].fr;
}
